default: &default
  services:
    away:
      overnight-boarding:
        default: true
      overnight-traveling: {}
      drop-in: {}
    work:
      doggy-day-care: {}
      dog-walking: {}

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
